# Generated by Django 3.2 on 2021-07-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eadd',
            new_name='eaddr',
        ),
    ]
